"""add

Revision ID: 16fe7f2b8220
Revises: bdedb07b3fcc
Create Date: 2022-09-27 15:34:05.427061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fe7f2b8220'
down_revision = 'bdedb07b3fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
