"""add_colum_id_auto

Revision ID: bdedb07b3fcc
Revises: 3aab494e99de
Create Date: 2022-09-27 15:23:13.285003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdedb07b3fcc'
down_revision = '3aab494e99de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'id')
    # ### end Alembic commands ###
